services:
  authenticator:
    build:
      context: ./services/authenticator
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - ./services/authenticator/.env
    environment:
      - POSTGRES_HOST=authenticator-db 
    secrets:
      - auth_private_key
      - auth_public_key
    depends_on:
      authenticator-db:
        condition: service_healthy
    extra_hosts:
        - "host.docker.internal:host-gateway"
  authenticator-db:
    restart: always
    build:
      context: ./services/authenticator/postgres
      dockerfile: Dockerfile
    env_file:
      - ./services/authenticator/.env
    ports:
      - 5432:5432
    volumes: 
      - postgres_data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  gym-core-db:
    image: mongo:7.0
    container_name: local-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:

secrets:
  auth_private_key:
    file: ./services/authenticator/keys/jwtRS256.key
  auth_public_key:
    file: ./keys/jwtRS256.key.pub