services:
  gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend-network
    depends_on:
      - authenticator
      - workout-core

  authenticator:
    build:
      context: ./services/authenticator
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./services/authenticator/.env
    environment:
      - POSTGRES_HOST=authenticator-db 
      - ROOT_PATH=/auth
    secrets:
      - auth_private_key
      - auth_public_key
    networks:
      - backend-network
    depends_on:
      authenticator-db:
        condition: service_healthy
      workout-core:
        condition: service_started

    extra_hosts:
        - "host.docker.internal:host-gateway"

  workout-core:
    build:
      context: ./services/workout-core
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # API
      - "4000:4000"  # GRPC
    env_file:
      - ./services/workout-core/.env
    secrets:
      - auth_public_key
    networks:
      - backend-network
    depends_on:
      workout-core-db:
        condition: service_healthy 
  
  authenticator-db:
    restart: always
    build:
      context: ./services/authenticator/postgres
      dockerfile: Dockerfile
    env_file:
      - ./services/authenticator/.env
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  workout-core-db:
    image: mongo:7.0
    container_name: local-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - ./services/workout-core/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mongo_data:

secrets:
  auth_private_key:
    file: ./services/authenticator/keys/jwtRS256.key
  auth_public_key:
    file: ./keys/jwtRS256.key.pub

networks:
  backend-network:
    driver: bridge